theme: minima
title: Alok Shrestha
author:
  name: Alok Shrestha
  email: connect@aloks.com.np
description: If I could describe me in few words, that wont justify my years of experience.

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: auto
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: facebook,       user_url: "https://www.facebook.com/aalookstha" }
    - { platform: instagram,      user_url: "https://www.instagram.com/aalookstha" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/aalooksth" }
    - { platform: twitter,        user_url: "https://twitter.com/aalooksth" }
    - { platform: telegram,       user_url: "https://t.me/aalooksth" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - connect.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag